# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTransaction():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_transaction(self):
    self.driver.get("http://localhost/jaas/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-grain").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\34u:nth-child(2) img").click()
    self.driver.find_element(By.ID, "type").click()
    dropdown = self.driver.find_element(By.ID, "type")
    dropdown.find_element(By.XPATH, "//option[. = 'Fruit']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) .image").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-sm-6").click()
    self.driver.find_element(By.LINK_TEXT, "Buy Now").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Baisani Venkata Jaswanth")
    self.driver.find_element(By.ID, "city").send_keys("Bengaluru")
    self.driver.find_element(By.ID, "mobile").send_keys("07019779028")
    self.driver.find_element(By.ID, "email").send_keys("jaswanth.baisani@gmail.com")
    self.driver.find_element(By.ID, "pincode").send_keys("560034")
    self.driver.find_element(By.ID, "addr").send_keys("Bangalore")
    self.driver.find_element(By.CSS_SELECTOR, "p > input").click()
  
