# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMyProfile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_myProfile(self):
    self.driver.get("http://localhost/jaas/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.LINK_TEXT, "My Profile: Ba").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
    self.driver.find_element(By.ID, "mobile").click()
    self.driver.find_element(By.ID, "mobile").send_keys("1231234511")
    self.driver.find_element(By.ID, "section").click()
    dropdown = self.driver.find_element(By.ID, "section")
    dropdown.find_element(By.XPATH, "//option[. = 'Band']").click()
    self.driver.find_element(By.CSS_SELECTOR, "center > .button").click()
    self.driver.find_element(By.LINK_TEXT, "My Profile: Ba").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, ".box > header").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".box > header")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".box > header").click()
    self.driver.find_element(By.NAME, "upload").click()
    self.driver.find_element(By.LINK_TEXT, "Retry").click()
    self.driver.find_element(By.ID, "profilePic").click()
    self.driver.find_element(By.ID, "profilePic").send_keys("C:\\fakepath\\WhatsApp Image 2023-02-24 at 19.55.49.jpg")
    self.driver.find_element(By.NAME, "upload").click()
    self.driver.find_element(By.CSS_SELECTOR, "center > .button").click()
    self.driver.find_element(By.ID, "mobile").click()
    self.driver.find_element(By.ID, "mobile").send_keys("1234567890")
    self.driver.find_element(By.CSS_SELECTOR, ".row").click()
    self.driver.find_element(By.CSS_SELECTOR, "center > .button").click()
  
