# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBuyerLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_buyerLogin(self):
    self.driver.get("http://localhost/jaas/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.CSS_SELECTOR, ".\\36u:nth-child(1) > .button").click()
    self.driver.find_element(By.ID, "uname").click()
    self.driver.find_element(By.ID, "uname").send_keys("Baisani")
    self.driver.find_element(By.ID, "pass").click()
    self.driver.find_element(By.ID, "pass").send_keys("Baisani")
    self.driver.find_element(By.CSS_SELECTOR, ".\\33u:nth-child(3) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\37u > input").click()
    self.driver.find_element(By.ID, "banner").click()
    self.driver.find_element(By.ID, "banner").click()
  
